### PR TITLE
upd: request header names are evaluated

### PR DESCRIPTION
**Pull request by theTestTube**

### CODE REVIEW

**Comment by theTestTube** [comment]
Dear @seymen, 

Are you having any trouble to merge my changes? I'm needing to incorporate this to a project and I still wanted to use apickli NPM module.

Thanks in advance.-

**Comment by seymen** [comment]
Sorry @theTestTube - time...

Is it possible to revert the changes you made to package.json so I can merge this in directly? I can then up the version and push to npm, hopefully together with PR74.

**Comment by seymen** [comment]
Changes merged.

**Comment by theTestTube** [comment]
@seymen Thanks for your merge response.

Still having two issues (should I open two issues for these trivial things?), one related to the httpbin.feature conflict, I've opened a new pull request at https://github.com/apickli/apickli/pull/76

**Pull request closed without merging**
