### PR TITLE
Verbose logging of Assertion failures where appropriate

### PR DESCRIPTION
**Pull request by seantdg**
Issue 28- Added optional verbose assertion results allowing Expected and Actual values to be displayed where appropriate.

@sauliuz @seymen : this is my first pass at this feature - just wanted to check that you agreed with my approach so far. Please note the 'options' object passed into apickli constructor and AssertionResult object being used. Comments welcome.

### CODE REVIEW

**Comment by sauliuz** [comment]
looks like this cannot be merged anymore @seantdg. 
we were also talking with @seymen that it would be great to have verbose and silent modes for running tests with apickli.
silent - only errors give you logs
debug or verbose - request / response data is loged out in console.

maybe needs additional issue created

**Comment by seantdg** [comment]
@sauliuz I agree - this PR was just to demonstrate the idea, we can take a look at refactoring the idea

**Comment by seymen** [comment]
No worries I pulled this locally and made necessary changes for it to merge today. I will share very soon. Just need to work on scenario tagging a bit.

**Comment by seymen** [comment]
PR #48

**Pull request closed without merging**
