### PR TITLE
Fixed Tests and Updated to work with Cucumber 2.0

### PR DESCRIPTION
**Pull request by bialesdaniel**
Fixed all the tests so that they pass. Changed the apickli-gherkin file in step_definitions to a require statement instead of a symlink. Changed the registerHandler methods to support cucumber.js 2.0 which no longer passes an event with a getPayloadItem method.

### CODE REVIEW

**Comment by seymen** [comment]
Thanks a lot for this @bialesdaniel. I was trying to spare some time to fix your original issue for the last couple of days.

I have just one problem: the tests that are failing for you are designed to be failed so that we can see the console outputs when tests fail. This is to assert that we see the correct error responses for failures.

If you see gulpfile, https://github.com/apickli/apickli/blob/master/source/Gulpfile.js#L5 is the task that most of us use to execute tests. The tests that should fail are implemented in a separate file and gulp task called `console-test`. 

So is it possible to update this PR with console-output.js reverted back to its previous form please?

**Comment by bialesdaniel** [comment]
Ah very interesting! I can absolutely do that. Would you mind if I added a brief CONTRIBUTING.md file which explains that too in order to prevent other people from making the same mistake I did. Unless that information is somewhere else that I missed

**Comment by seymen** [comment]
I wouldn't mind at all :)

**Comment by bialesdaniel** [comment]
I made those updates. Let me know how they look.

**Pull request merged**
