### PR TITLE
setting headers using table

### PR DESCRIPTION
**Pull request by seymen**
/cc @seanapigee @sauliuz

### CODE REVIEW

**Comment by jaffamonkey** [comment]
Excellent, much more user-friendly :)

**Comment by sauliuz** [comment]
looking good!

**Comment by seantdg** [comment]
The only limitation is if multiple headers with the same name are passed, we overwrite instead of merging into a comma-separated list. 

e.g. 
| name | value |
| Authorization | Bearer abc |
| Authorization | Basic def |

will only set Basic. Users will have to be aware and change this to

| name | value |
| Authorization | Bearer abc, Basic def |


Changes look good though! :)

**Comment by seymen** [comment]
@seantdg I am not sure what the correct behaviour should be for duplicate header names.

**Comment by seantdg** [comment]
@seymen i would expect merging them into a comma separated list...

https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

"Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list (...) It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message..."

**Pull request merged**
