### PR TITLE
cucumber upgrade to v7 without grunt and gulp dependencies

### LINKED ISSUE #180: Compatibility with @cucumber/cucumber:^7
Hi,

Cucumber changed from namespace some time ago moving:
- from `cucumber`
- to `@cucumber/cucumber`

Currently, we're stuck on cucumber v5 because apickli isn't imported the new namespace.

package.json from apickli
```json
{
    "devDependencies": {
        "cucumber": "^5"
    }
}
```

Cucumber import from apickli (apickli-gherkin.js)
```js
const {Before, Given, When, Then} = require('cucumber');
```

My package.json
```json
{
    "dependencies": {
        "apickli": "2.3.4",
        "@cucumber/cucumber": "7.2.1"
    }
}
```

My error
```bash
Error: Cannot find module 'cucumber'
Require stack:
- xxx/node_modules/apickli/apickli-gherkin.js
- xxx/features/step_definitions/api.js
- xxx/node_modules/@cucumber/cucumber/lib/cli/index.js
- xxx/node_modules/@cucumber/cucumber/lib/cli/run.js
- xxx/node_modules/@cucumber/cucumber/bin/cucumber-js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (xxx/node_modules/apickli/apickli-gherkin.js:6:37)
```

Could you upgrade your code & your dependencies to depend on the latest `@cucumber/cucumber` package?

### PR DESCRIPTION
**Pull request by seymen**
fixes #180 

- do you agree that this is a backwards incompatible change - hence v3.0.0?
- gulp and grunt dependencies are currently too heavy to support with no additional benefit to the project. They can still be used without us publishing docs and supporting the libs. Proposal with this PR would be to remove them out of the project. Any objections?

@laughingbiscuit @sauliuz ^

### CODE REVIEW

**Comment by sauliuz** [comment]
removing dependency on gulp is nice & lean approach - however, we are losing JS code linting / eslint run which was baked into gulp which is not great.

👍  - for major version update to v3

**Review by geertendoornenbal — APPROVED** [review]

**Comment by seymen** [comment]
How about now @sauliuz?

**Comment by sauliuz** [comment]
looks good @seymen, thumbs up for npm scripts.

**Review by sauliuz — APPROVED** [review]
👍

**Pull request merged**
